### ISSUE TITLE
Deleting an Input plugin leaves "no name" item

### ISSUE THREAD

**Issue by firthm01** [ebu/ear-production-suite#75] opened 2021-03-17 22:02 UTC
If the Scene GUI is closed when an input plugin is deleted, the item is still in the programme when the Scene GUI is opened, but the name is "no name"

Steps;
- Load a saved session with EPS plugins (not sure if necessary, but it's how I could reliably reproduce it)
- With the Scene GUI closed, delete an input plugin which was in the current programme.
- Open the Scene GUI - the item is still in the programme and named "no name"

Could be due to bad store refresh like issue #72

**Comment by ial-sebastian** [comment] 2021-03-18 20:59
Hi, i think the fix for the original issue 28 should already solve this, but wasn't merged due to a conflict. I guess my attempt to solve this conflict didn't trigger any message, so the merge request is still pending. Hopefully it will now be able to be merged and resolve itself.

**Comment by rsjtaylor** [comment] 2021-03-26 14:56
Yup, #28 has now been fixed via PR #78, I can no longer reproduce this issue in main.

**Closed by rsjtaylor** 2021-03-26 14:56 UTC
Labels: bug
