### ISSUE TITLE
ADM Export Crash

### ISSUE THREAD

**Issue by mozzak** [ebu/ear-production-suite#81] opened 2021-04-01 15:10 UTC
Hi:

I have an dolby atmos file. It opens fine via the Import and plays good as well. 
The playback sounds "phasy" compared to like the dolby renderer but that is a different topic.

The issue at hand is the export ADM feature. As soon as I open the export screen and select ADM file format
Reaper crashes immediately with a Microsoft Visual C++ Runtime Error. This happens everytime (see attachment).

Any help or advise would be appreciated.

Thanks,
Michael

![Reaper Export Error](https://user-images.githubusercontent.com/730538/113315004-d4769880-92da-11eb-814f-86b875d839a9.PNG)

**Comment by firthm01** [comment] 2021-04-01 16:05
Hi Michael, thanks for letting us know about this. I'm not sure what the issue might be at this stage but it's obviously something we'd like to fix. 
Do you have an RPP (Reaper project file) we could use to recreate the bug? There is no need to include the audio assets - just the RPP. You should be able to attach it to this issue by putting it in a ZIP and dragging and dropping in to the text box at the bottom of this page.

**Comment by mozzak** [comment] 2021-04-01 19:31
Thanks for getting back to me.

It seems it has to do with setting the EAR Direct Speakers to 7.1.2H. In that format export crashes. Changing it to like 7.1.4 no crash.

Project File attached.

On a slight different note: The website states:

"Currently the files are not compatible with the Dolby Atmos Production Suite...."

We are in the project of starting with Dolby Atmos and trying to pick our setup. We like reaper a lot but would need to be able to export an ADM that works with the Dolby Atmos Renderer. Any plans to support this in the future and if so when? 


[Reaper ADM Test.zip](https://github.com/ebu/ear-production-suite/files/6246044/Reaper.ADM.Test.zip)

**Comment by chrispike-bbc** [comment] 2021-04-08 10:21
Dear Michael,

Regarding Dolby Atmos compatibility. The cause of this problem is in the different ADM profiles that are used by each set of tools. The ADM is a very flexible metadata model and profiles provide limitations on the configuration of the audio format. Unfortunately, we are in a position of having more than one profile in use and not yet having defined conversions between them.

The EAR Production Suite uses the [EBU ADM Production profile](https://tech.ebu.ch/docs/tech/tech3392.pdf), whereas the Dolby Atmos tools use [Dolby’s own profile specification](https://developer.dolby.com/technology/dolby-atmos/adm-atmos-profile/). The EAR Production Suite provides a conversion from the Dolby profile on import, however it only exports to the EBU Production profile and the Dolby tools do not accept this as input. 

I appreciate that this may be frustrating. We want to enable a way to convert the files for use in Dolby’s production and delivery tools in future, perhaps in a separate standalone tool, and hopefully working in partnership with Dolby. However, we cannot say when this will be available at this time.

The ADM is still an emerging format and interoperability between tools is not yet good enough. That’s part of the reason that we have developed the EAR Production Suite, to enable interoperability testing and improve the compatibility of tools. However this will take time yet. My apologies.

I also spotted your comment about phasiness of the mix after import from the Dolby tools. That is something we should investigate when we are able to access our studio again.

**Comment by firthm01** [comment] 2021-04-08 10:30
> It seems it has to do with setting the EAR Direct Speakers to 7.1.2H. In that format export crashes. Changing it to like 7.1.4 no crash.

Ah yes - you are right. There was a bug in there related to 7.1.2H support. There is a fix ready for that which will be in our next beta, along with a number of other fixes. We hope to release this in the within the next few weeks.

**Comment by rsjtaylor** [comment] 2021-08-13 13:14
This is now fixed in main, although render is currently impossible due to a different bug that will be resolved by #109

**Closed by rsjtaylor** 2021-08-13 13:14 UTC
